- name: Create TEST.TEST in /tmp
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Create TEST.TEST file
      file:
        path: /tmp/TEST.Become
        state: touch
        mode: '0644'
