- name: Create TEST.TEST in /tmp
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Who am I
      command: whoami
      register: out

    - debug:
        var: out.stdout
    - name: Create TEST.TEST file
      file:
        path: /root/TEST.Become
        state: touch
        mode: '0644'
